In [21]:
from scipy.stats import chi2_contingency
tabla_contingencia= [[20, 30, 15], [20, 15, 30]]
stat, p, dof, expected = chi2_contingency(tabla_contingencia)
alfa= 0.05

In [22]:
p

0.006737946999085468

In [23]:
print('Significancia=%.3f, p=%.3f' % (alfa, p))

Significancia=0.050, p=0.007

In [24]:
if p <= alfa:
  print('Variables son asociadas (Rechazo de H0: Caracteristicas no son independientes)')
else:
  print('Variables no son asociadas (Falló Rechazo de H0: Características son independientes)')

Variables son asociadas (Rechazo de H0: Caracteristicas no son independientes)

**Detectando registros duplicado**s

In [25]:
import pandas as pd

data = {'Id': [1, 2, 3, 4, 5, 6, 7, 7], 'Primer_nombre': ['Angela', 'Adrian', 'Theodoro', 'Angela',
'Adrian', 'Beatriz', 'Olivia', 'Olivia'], 'Primer_apellido': ['Castro', 'Guzman', 'Rivadeneira',
'Castillo', 'Casas', 'Perez', 'Apraez', 'Apraez'], 'Edad': [27, 31, 36, 27, 53, 48, 36, 36],
'Estatura': [1.67, 1.80, 1.61, 1.77, 1.88, 1.69, 1.62, 1.62]}

df = pd.DataFrame(data, columns = ['Id', 'Primer_nombre', 'Primer_apellido', 'Edad', 'Estatura'])

In [26]:
df

   Id Primer_nombre Primer_apellido  Edad  Estatura
0   1        Angela          Castro    27      1.67
1   2        Adrian          Guzman    31      1.80
2   3      Theodoro     Rivadeneira    36      1.61
3   4        Angela        Castillo    27      1.77
4   5        Adrian           Casas    53      1.88
5   6       Beatriz           Perez    48      1.69
6   7        Olivia          Apraez    36      1.62
7   7        Olivia          Apraez    36      1.62

Detectar duplicados

In [27]:
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7     True
dtype: bool

Eliminar duplicados

In [28]:
df = df.drop_duplicates()

In [29]:
df

   Id Primer_nombre Primer_apellido  Edad  Estatura
0   1        Angela          Castro    27      1.67
1   2        Adrian          Guzman    31      1.80
2   3      Theodoro     Rivadeneira    36      1.61
3   4        Angela        Castillo    27      1.77
4   5        Adrian           Casas    53      1.88
5   6       Beatriz           Perez    48      1.69
6   7        Olivia          Apraez    36      1.62

**Reemplazo de valores nulos**

In [30]:
# Carga la biblioteca
from pandas import read_csv
# Función que permite leer un archivo CSV y asignarlo a un Dataframe
# Descargar desde https://www.kaggle.com/datasets/saurabh00007/diabetescsv
dataset = read_csv('diabetes.csv')
# Resumen de los datos
dataset.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

se observa que hay atributos que tienen un valor mínimo de cero

In [31]:
print(dataset.head(20))

    Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0             6      148             72             35        0  33.6
1             1       85             66             29        0  26.6
2             8      183             64              0        0  23.3
3             1       89             66             23       94  28.1
4             0      137             40             35      168  43.1
5             5      116             74              0        0  25.6
6             3       78             50             32       88  31.0
7            10      115              0              0        0  35.3
8             2      197             70             45      543  30.5
9             8      125             96              0        0   0.0
10            4      110             92              0        0  37.6
11           10      168             74              0        0  38.0
12           10      139             80              0        0  27.1
13            1      189             60             23      846  30.1
14            5      166             72             19      175  25.8
15            7      100              0              0        0  30.0
16            0      118             84             47      230  45.8
17            7      107             74              0        0  29.6
18            1      103             30             38       83  43.3
19            1      115             70             30       96  34.6

    DiabetesPedigreeFunction  Age  Outcome
0                      0.627   50        1
1                      0.351   31        0
2                      0.672   32        1
3                      0.167   21        0
4                      2.288   33        1
5                      0.201   30        0
6                      0.248   26        1
7                      0.134   29        0
8                      0.158   53        1
9                      0.232   54        1
10                     0.191   30        0
11                     0.537   34        1
12                     1.441   57        0
13                     0.398   59        1
14                     0.587   51        1
15                     0.484   32        1
16                     0.551   31        1
17                     0.254   31        1
18                     0.183   33        0
19                     0.529   32        1

In [32]:
# Reemplaza 0 por 'nan'
dataset = dataset.replace(0, 'nan')

In [33]:
# Imprimir los 20 primeros datos
print(dataset.head(20))

   Pregnancies Glucose BloodPressure SkinThickness Insulin   BMI  \
0            6     148            72            35     nan  33.6
1            1      85            66            29     nan  26.6
2            8     183            64           nan     nan  23.3
3            1      89            66            23      94  28.1
4          nan     137            40            35     168  43.1
5            5     116            74           nan     nan  25.6
6            3      78            50            32      88  31.0
7           10     115           nan           nan     nan  35.3
8            2     197            70            45     543  30.5
9            8     125            96           nan     nan   nan
10           4     110            92           nan     nan  37.6
11          10     168            74           nan     nan  38.0
12          10     139            80           nan     nan  27.1
13           1     189            60            23     846  30.1
14           5     166            72            19     175  25.8
15           7     100           nan           nan     nan  30.0
16         nan     118            84            47     230  45.8
17           7     107            74           nan     nan  29.6
18           1     103            30            38      83  43.3
19           1     115            70            30      96  34.6

    DiabetesPedigreeFunction  Age Outcome
0                      0.627   50       1
1                      0.351   31     nan
2                      0.672   32       1
3                      0.167   21     nan
4                      2.288   33       1
5                      0.201   30     nan
6                      0.248   26       1
7                      0.134   29     nan
8                      0.158   53       1
9                      0.232   54       1
10                     0.191   30     nan
11                     0.537   34       1
12                     1.441   57     nan
13                     0.398   59       1
14                     0.587   51       1
15                     0.484   32       1
16                     0.551   31       1
17                     0.254   31       1
18                     0.183   33     nan
19                     0.529   32       1

**Normalizacion**

In [34]:
print(dataset.head(20))

   Pregnancies Glucose BloodPressure SkinThickness Insulin   BMI  \
0            6     148            72            35     nan  33.6
1            1      85            66            29     nan  26.6
2            8     183            64           nan     nan  23.3
3            1      89            66            23      94  28.1
4          nan     137            40            35     168  43.1
5            5     116            74           nan     nan  25.6
6            3      78            50            32      88  31.0
7           10     115           nan           nan     nan  35.3
8            2     197            70            45     543  30.5
9            8     125            96           nan     nan   nan
10           4     110            92           nan     nan  37.6
11          10     168            74           nan     nan  38.0
12          10     139            80           nan     nan  27.1
13           1     189            60            23     846  30.1
14           5     166            72            19     175  25.8
15           7     100           nan           nan     nan  30.0
16         nan     118            84            47     230  45.8
17           7     107            74           nan     nan  29.6
18           1     103            30            38      83  43.3
19           1     115            70            30      96  34.6

    DiabetesPedigreeFunction  Age Outcome
0                      0.627   50       1
1                      0.351   31     nan
2                      0.672   32       1
3                      0.167   21     nan
4                      2.288   33       1
5                      0.201   30     nan
6                      0.248   26       1
7                      0.134   29     nan
8                      0.158   53       1
9                      0.232   54       1
10                     0.191   30     nan
11                     0.537   34       1
12                     1.441   57     nan
13                     0.398   59       1
14                     0.587   51       1
15                     0.484   32       1
16                     0.551   31       1
17                     0.254   31       1
18                     0.183   33     nan
19                     0.529   32       1

obtener los datos normalizados:

In [35]:
from sklearn.preprocessing import MinMaxScaler
min_max_scaler = MinMaxScaler()
X_norm = min_max_scaler.fit_transform(dataset)
X_norm
diabetes_norm = pd.DataFrame(X_norm)
diabetes_norm.describe()

,0,1,2,3,4,5,6,7,8
count,657.000000,763.000000,733.000000,541.000000,394.000000,757.000000,768.000000,768.000000,268.0
mean,0.218417,0.501205,0.493930,0.240798,0.170130,0.291564,0.168179,0.204015,0.0
std,0.201081,0.197004,0.126349,0.113880,0.142759,0.141615,0.141473,0.196004,0.0
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
25%,0.062500,0.354839,0.408163,0.163043,0.074820,0.190184,0.070773,0.050000,0.0
50%,0.187500,0.470968,0.489796,0.239130,0.133413,0.288344,0.125747,0.133333,0.0
75%,0.375000,0.625806,0.571429,0.315217,0.211538,0.376278,0.234095,0.333333,0.0
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.0

Normalización Z-score

In [36]:
from sklearn.preprocessing import StandardScaler
standar_scaler = StandardScaler()
X_norm2 = standar_scaler.fit_transform(dataset)
df_diabetes_norm2 = pd.DataFrame(X_norm2)
df_diabetes_norm2.describe()

,0,1,2,3,4,5,6,7,8
count,6.570000e+02,7.630000e+02,7.330000e+02,5.410000e+02,3.940000e+02,7.570000e+02,7.680000e+02,7.680000e+02,268.0
mean,-6.218601e-17,1.070936e-16,-4.871047e-16,-3.447643e-17,1.127130e-17,3.660656e-16,2.451743e-16,1.931325e-16,0.0
std,1.000762e+00,1.000656e+00,1.000683e+00,1.000925e+00,1.001271e+00,1.000661e+00,1.000652e+00,1.000652e+00,0.0
min,-1.087043e+00,-2.545803e+00,-3.911938e+00,-2.116442e+00,-1.193241e+00,-2.060204e+00,-1.189553e+00,-1.041549e+00,0.0
25%,-7.759862e-01,-7.434474e-01,-6.792777e-01,-6.834067e-01,-6.684780e-01,-7.163537e-01,-6.889685e-01,-7.862862e-01,0.0
50%,-1.538716e-01,-1.535857e-01,-3.274557e-02,-1.465704e-02,-2.575192e-01,-2.275351e-02,-3.001282e-01,-3.608474e-01,0.0
75%,7.793003e-01,6.328967e-01,6.137865e-01,6.540926e-01,2.904259e-01,5.985967e-01,4.662269e-01,6.602056e-01,0.0
max,3.889873e+00,2.533562e+00,4.008080e+00,6.672840e+00,5.820456e+00,5.005848e+00,5.883565e+00,4.063716e+00,0.0

**Transformación nominal a binario**

In [37]:
import pandas as pd
data = [["Juan", "Hombre"], ["Pedro", "Hombre"],
["Angie", "Mujer"], ["Paola", "Mujer"],
["Dago", "Hombre"]]

In [38]:
data_frame = pd.DataFrame(data, columns=["Nombre", "Sexo"])
print(data_frame)

  Nombre    Sexo
0   Juan  Hombre
1  Pedro  Hombre
2  Angie   Mujer
3  Paola   Mujer
4   Dago  Hombre

In [39]:
df_one = pd.get_dummies(data_frame["Sexo"])
print(df_one)

   Hombre  Mujer
0    True  False
1    True  False
2   False   True
3   False   True
4    True  False

In [40]:
df_one = pd.get_dummies(data_frame["Nombre"])
print(df_one)

   Angie   Dago   Juan  Paola  Pedro
0  False  False   True  False  False
1  False  False  False  False   True
2   True  False  False  False  False
3  False  False  False   True  False
4  False   True  False  False  False